### DISCUSSION TITLE
Passing overrides as YML file in Docker Compose?

### DISCUSSION THREAD

**Discussion by tyteen4a03** [SoftInstigate/restheart#515] [Q&A]
How do I pass overrides as YML files in Docker Compose? There's no obvious entrypoint from what I can see.

**Comment by ujibang** [comment]
You can configure RESTHeart using a configuration override file as documented [here](https://restheart.org/docs/configuration#2-using-a-configuration-override-file).

To mount the override file, use the `-v` option in Docker, for example at `/opt/restheart/etc/conf-overrides.yml`. Then, specify the file with the `-o` RESTHeart option.

Here is an example command:

```bash
docker run --rm -p "8080:8080" -e RHO="" -v /path/to/conf-overrides.yml:/opt/restheart/etc/conf-overrides.yml softinstigate/restheart -o etc/conf-overrides.yml
```

**NOTE:**

The RESTHeart Docker image uses the `RHO` environment variable, which takes precedence over the configuration override file. To ensure the configuration override file is used, include `-e RHO=""` in your `docker run` command.

**Reply by tyteen4a03** [reply]
Does this work in a Docker Compose context?

**Reply by ujibang** [reply]
yes, you define a docker compose conf file like

```
services:
    restheart:
        image: softinstigate/restheart
        volumes:
            - /path/to/conf-overrides.yml:/opt/restheart/etc/conf-overrides.yml
        command: ["-o", "/opt/restheart/etc/conf-overrides.yml"] 
        ports:
            - "8080:8080"
        environment:
            RHO: ""
```
