### DISCUSSION TITLE
Can I configure restheart with a pre-shared key to be used as auth mechanism ?

### DISCUSSION THREAD

**Discussion by pankajagarwal** [SoftInstigate/restheart#551] [Q&A] [answered]
I am wondering if restheart supports it out of the box and in all the great documentation on all the fancy and useful options to secure the endpoint, i am wondering if also supports the very basic pre-shared key based auth as well.

I can put a nginx in front and possibly add that but trying to avoid adding any component in the mix. 

Please share your experiences and suggestions here.

**Comment by ujibang** [comment, marked as answer]
Hello @pankajagarwal 

I suggest you a couple of options:

## use the `jwtAuthenticationMechanism`. 

enable it and generate few JWT that you can use as pre-shared keys (you can use jwt.io to generate tokens)

```yml
jwtAuthenticationMechanism:
    enabled: true
    algorithm: HS256
    key: secret
    base64Encoded: false
    usernameClaim: sub
    rolesClaim: roles
    fixedRoles:
      - the-role
    issuer: myIssuer
    audience: myAudience
```

In this case, clients authenticate passing the `Authorization` header as `Bearer <jwt>`

## use the `fileRealmAuthenticator` defining users with pre-shared ids and passwords

```yml
fileRealmAuthenticator:
    enabled: true
    users:
    - userid: key1
      password: a-very-long-pre-shared-key
      roles: [the-role]
```

In thia case, clients authenticate via Basic authentication passing the `Authorization` header as `Basic base64(<userid> + ':' + <password>)`
