### DISCUSSION TITLE
performance issues with a request rate of only 1500

### DISCUSSION THREAD

**Discussion by pankajagarwal** [SoftInstigate/restheart#553] [Q&A]
Any one using restheart would like to share the performance enhancements they have tried and worked for them ?

One weird issue I am noticing with restheart and mongo atlas (sharded M60), some queries with specific _id value are taking upto 17 seconds to respond from restheart side.

here's the config file with information redacted ... 
```
---
http-listener:
  enabled: true
  host: 0.0.0.0
  port: 8080

https-listener:
  enabled: false
  host: localhost
  port: 4443

ajp-listener:
  enabled: false
  host: localhost
  port: 8009

tokenBasicAuthMechanism:
  enabled: true

basicAuthMechanism:
  enabled: true
  authenticator: fileRealmAuthenticator

jwtAuthenticationMechanism:
  enabled: false

digestAuthMechanism:
  enabled: false

identityAuthMechanism:
  enabled: false

fileRealmAuthenticator:
  enabled: true
  users:
    - userid: redacted
      password: redacted
      roles: [admin]
    - userid: redacted1
      password: redacted
      roles: [user]

mongoRealmAuthenticator:
  enabled: false

authCookieSetter:

authCookieHandler:

authCookieRemover:

fileAclAuthorizer:
  enabled: true
  permissions:
    - role: admin
      predicate: path-prefix('/api') or path-prefix('/metrics')
      priority: 0
      "mongo": {
        "allowManagementRequests": true
      }
    - role: user
      predicate: path-prefix('/api') or path-prefix('/metrics')
      priority: 1

mongoAclAuthorizer:
  enabled: false

originVetoer:
  enabled: false

fullAuthorizer:
  enabled: false
  authentication-required: true

rndTokenManager:
  enabled: true
  srv-uri: /tokens
  ttl: 3600

jwtTokenManager:
  enabled: false
  key: secret
  srv-uri: /tokens
  issuer: restheart.org
  audience: null
  account-properties-claims:

mclient:
  connection-string: mongodb://127.0.0.1

mongo:
  enabled: true
  uri: /
  mongo-mounts:
    - what: /redacted
      where: /api
  default-representation-format: STANDARD
  etag-check-policy:
    db: REQUIRED_FOR_DELETE
    coll: REQUIRED_FOR_DELETE
    doc: OPTIONAL
  get-collection-cache-enabled: true
  get-collection-cache-size: 100
  aggregation-check-operators: true
  default-pagesize: 100
  max-pagesize: 1_000
  local-cache-enabled: true
  schema-cache-enabled: true

graphql:
  enabled: false
proxies:
static-resources:
authTokenService:
  uri: /tokens
ping:
  enabled: true
  msg: pong
  enable-extended-response: false

roles:
  uri: /roles

filterOperatorsBlacklist:
  blacklist: [ "$where" ]
  enabled: false

bruteForceAttackGuard:
  enabled: false

xPoweredBy:
  enabled: false

dateHeader:
  enabled: false

logging:
  log-level: INFO
  log-to-console: true
  ansi-console: true
  log-to-file: false
  log-file-path: restheart.log
  packages: [ "org.restheart", "com.restheart" ]
  full-stacktrace: false
  requests-log-mode: 1
  tracing-headers:

metrics:
  enabled: true
  uri: /metrics

requestsMetricsCollector:
  enabled: true
  include: [ "/api*" ]
  exclude: [ "/metrics", "/metrics/*" ]

jvmMetricsCollector:
  enabled: true

core:
  name: default
  plugins-directory: plugins
  plugins-packages: []
  plugins-scanning-verbose: false
  base-url: http://rh-use1.redacted.xyz:8080
  io-threads: 0
  workers-scheduler-parallelism: 0
  workers-scheduler-max-pool-size: 256
  buffers-pooling: true
  buffer-size: 16364
  direct-buffers: true
  force-gzip-encoding: false
  allow-unescaped-characters-in-url: true

connection-options:
  ENABLE_HTTP2: true
  MAX_HEADER_SIZE: 1048576
  MAX_ENTITY_SIZE: -1
  MULTIPART_MAX_ENTITY_SIZE: -1
  IDLE_TIMEOUT: -1
  REQUEST_PARSE_TIMEOUT: -1
  NO_REQUEST_TIMEOUT: -1
  MAX_PARAMETERS: 1_000
  MAX_HEADERS: 200
  MAX_COOKIES: 200
  URL_CHARSET: UTF-8
  ALWAYS_SET_KEEP_ALIVE: true
```
