### ISSUE TITLE
the restHeart provides custom url transform to real resource URL?

### ISSUE THREAD

**Issue by jiyangyang0319** [SoftInstigate/restheart#277]
I want transform custom url to real resource URL，and restHeart provides this function？

**Comment by ujibang** [comment]
look at the [configuration file], the `mongo-mounts` options allow for URL rewrite

``` yml
# Use mongo-mounts to bind URls to mongodb resources using the out-of-the-box URL rewrite feature.
# The where URI can be an absolute path (eg. /api) or path template (eg. /{foo}/bar/*). 
# The values of the path templates properties are available:
# - in the what property (e.g. what: /{foo}_db/coll) 
# - programmatically from RequestContext.getPathTemplateParamenters() method.
# It is not possible to mix absolute paths and path templates: where URIs need to be either all absolute paths or all path templates.
mongo-mounts:
    - what: "*"
      where: /
```

for instance, the following configuration maps the `db.coll` collection to the URI `/api`

``` yml
mongo-mounts:
    - what: /db/coll
      where: /api
```
