### ISSUE TITLE
How to do join in restheart

### ISSUE THREAD

**Issue by prakashsubramaniam** [SoftInstigate/restheart#280]
Hi Team,

I want to refer two collection and need to retrieve the data from mongo db and I have created the aggregation meta data in mongo and passing the avars variable also. But unforutnately I keep on getting an error as "Query does not exist". I have provided the sample which I tried for aggregation first as per the issue101 below,

Aggregation MetaData:
----------------------------
``` json
{
    "_id" : ObjectId("5af121a8"),
    "aggrs" : [ 
        {
            "type" : "pipeline",
            "uri" : "totalitem",
            "stages" : [ 
                {
                    "_$match" : {
                        "Item" : {
                            "_$var" : "Item"
                        }
                    }
                }, 
                {
                    "_$group" : {
                        "_id" : "$Item",
                        "total" : {
                            "_$sum" : "$Amount"
                        }
                    }
                }
            ]
        }
    ]
}
```

URLs I used:
--------------

```
https://10.200.1.168:4443/cache/A/_aggrs/totalitem?avars={'Item':'a'}

https://10.200.1.168:4443/cache/A/_aggrs/totalitem?'avars={"Item":"a"}'

https://10.200.1.168:4443/cache/A/_aggrs/totalitem?avars='{"Item":"a"}'

https://10.200.1.168:4443/cache/A/_aggrs/totalitem?avars={"Item":"a"}
```

Error Message for all the above url:
----------------------------------------
``` json
{"http status code":404,"http status description":"Not Found","message":"query does not exist"}
```

Mongo DB version = 3.6
Restheart Version: 3.1.1

Please let me know if you need more information regarding the issue.

**Comment by prakashsubramaniam** [comment]
Hi Team,

Below is the exact scenario what I want to perform in restheart,

employment collection data:
---------------------------
{
    "_id" : ObjectId("5af12e703"),
    "employeeId" : "P876",
    "employeeName" : "Mark",
    "employeeSurname" : "Smith",
    "gender" : "Male",
    "age" : "42",
    "employmentType" : "Permanent"
}


{
    "_id" : ObjectId("5af12e"),
    "employeeId" : "P878",
    "employeeName" : "Andrew",
    "employeeSurname" : "Ken",
    "gender" : "Male",
    "age" : "38",
    "employmentType" : "Permanent"
}


designation collection data:
----------------------------

{
    "_id" : ObjectId("5af12eaa"),
    "id" : "P876",
    "designation" : "TechnicalArchitect",
    "department" : "ApplicationDevelopment",
    "level" : "A5"
}

{
    "_id" : ObjectId("5af12"),
    "id" : "P878",
    "designation" : "DesignArchitect",
    "department" : "ApplicationDevelopment",
    "level" : "A4"
}

aggregation Meta Data in Employment Collection:
------------------------------------------------
 { "aggrs" : [ 
        {
            "stages" : [ 
                {
                    "_$lookup" : {
                        "from" : "designation",
                        "localField" : "employeeId",
                        "foreignField" : "id",
                        "as" : "employeeInfo"
                    }
                }
            ],
            "type" : "pipeline",
            "uri" : "employeeDetails"
        }
    ]
}

restheart URL: https://00.000.0.000:4443/cache/employment/_aggrs/employeeDetails
--------------

Error Message: {"http status code":404,"http status description":"Not Found","message":"query does not exist"}
--------------

ExpectedOutput:
---------------

{  
   "employeeInfo":{  
      "employeeId":"P876",
      "employeeName":"Mark",
      "employeeSurname":"Smith",
      "gender":"Male",
      "age":"42",
      "employmentType":"Permanent",
      "designation":"TechnicalArchitect",
      "department":"ApplicationDevelopment",
      "level":"A5"
   }
}

Could you please help me to achieve this?

**Comment by ujibang** [comment]
do you have anything in the restheart log when you `GET /cache/employment/_aggrs/employeeDetails`

**Comment by prakashsubramaniam** [comment]
Hi Ujibang,

Sorry, I did not check the restheart log as it is in development server and also could you please let me know what is the path for error log?

**Comment by ujibang** [comment]
logging is configured by this section of the conf file

if you didn't touch it, it should be restheart.log in system temporary directory

``` yml
#### Logging

# enable-log-console: true => log messages to the console (default value: true)
# enable-log-file: true => log messages to a file (default value: true)
# log-file-path: to specify the log file path (default value: restheart.log in system temporary directory)
# log-level: to set the log level. Value can be OFF, ERROR, WARN, INFO, DEBUG, TRACE and ALL. (default value is INFO)
# requests-log-level: log the request-response. 0 => no log, 1 => light log, 2 => detailed dump
# WARNING: use requests-log-level level 2 only for development purposes, it logs user credentials (Authorization and Auth-Token headers)

enable-log-file: false
#log-file-path: /tmp/restheart.log
enable-log-console: true
log-level: INFO
requests-log-level: 1
```
