### ISSUE TITLE
Healthcheck for docker container

### ISSUE THREAD

**Issue by italktothewind** [SoftInstigate/restheart#382]
Currently it's impossible to do a healthcheck in the Restheart container because you can't execute something like a curl. Please provide some method to check the container's health.

**Comment by mkjsix** [comment]
If you want to healthcheck RESTHeart then you can call the `/ping` URI. I don't see why you should want to check the container health from within the container itself, it's not a good practice. If you instead meant to check the health of another container, then it's not a good practice either, you should monitor containers with an external monitoring system.
 If I misunderstood what you mean please be more specific in your request.

**Comment by italktothewind** [comment]
I have the following problem. I have this docker compose:

```
  mongodb:
    image: mongo:4.2
    ports:
      - 27017:27017

  restheart:
    image: softinstigate/restheart:3.10.0
    ports:
      - 8082:8080
    volumes:
      - ./restheart:/opt/restheart/etc:ro
    depends_on:
      - mongodb
    healthcheck:
      test: ["NONE"]
```

I want to put a healthcheck in restheart (instead of NONE), but all the commands I tried failed. Then I tried to execute something like curl using docker exec, but I got:

> OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"curl\": executable file not found in $PATH": unknown
