### ISSUE TITLE
mongoRealmAuthenticator not working ? 

### ISSUE THREAD

**Issue by trunglh88** [SoftInstigate/restheart#405]
Hi all,
i'm a newbie and try to run a demo restheart with mongoRealmAuthenticator.
I using Docker to setup Restheart, and after container running i try a simple request to  [http://localhost:8080/users](http://localhost:8080/users) not include Basic Authentication header  but request still return 

`[
  {
    "_id": "admin",
    "roles": [
      "admin"
    ]
  }
]`

## Expected Behavior
Request return 401 Unauthorized

## Environment
I'm using Docker on Windows 10

My restheart.yml

```
auth-mechanisms:
  tokenBasicAuthMechanism:
    enabled: true
  basicAuthMechanism:
    enabled: true
    authenticator: mongoRealmAuthenticator
  jwtAuthenticationMechanism:
    enabled: false
    algorithm: HS256
    key: secret
    base64Encoded: false
    usernameClaim: sub
    rolesClaim: roles
    fixedRoles:
#      - admin
    issuer: myIssuer
    audience: myAudience
  digestAuthMechanism:
    enabled: true
    realm: RESTHeart Realm
    domain: localhost
    authenticator: mongoRealmAuthenticator
  identityAuthMechanism:
    enabled: false
    username: admin
    roles:
      - admin
      - user
  ```
