### ISSUE TITLE
v6.0.2, Docker, ERROR org.restheart.Bootstrapper (org.restheart.mongodb.db.MongoClientSingleton)

### ISSUE THREAD

**Issue by mcardia** [SoftInstigate/restheart#410]
```
restheart    |  13:46:55.065 [main] ERROR org.restheart.Bootstrapper - Linkage error executing initializer changeStreamActivator Check that it was compiled against restheart-commons v6.0.2
restheart    |  java.lang.ExceptionInInitializerError: null
restheart    |  at org.restheart.mongodb.db.MongoClientSingleton.getInstance(MongoClientSingleton.java:76)
restheart    | Caused by: java.lang.IllegalStateException: not initialized
restheart    |  at org.restheart.mongodb.db.MongoClientSingleton.<init>(MongoClientSingleton.java:97)
restheart    | 13:46:55.065 [main] ERROR org.restheart.Bootstrapper - Error executing initializer txnsActivator An external dependency is missing. Copy the missing dependency jar to the plugins directory to add it to the classpath
restheart    |  java.lang.NoClassDefFoundError: Could not initialize class org.restheart.mongodb.db.MongoClientSingleton$MongoClientSingletonHolder
restheart    |  at org.restheart.mongodb.db.MongoClientSingleton.getInstance(MongoClientSingleton.java:76)
```

## Expected Behavior

We don't expect to get errors messages in the service

## Current Behavior

ERROR org.restheart.Bootstrapper - Error executing initializer txnsActivator An external dependency is missing. Copy the missing dependency jar to the plugins directory to add it to the classpath
restheart    |  java.lang.NoClassDefFoundError: Could not initialize class org.restheart.mongodb.db.MongoClientSingleton$MongoClientSingletonHolder

## Context

Starting the service

My Compose:

```
version: "3"

services:
  restheart:
    image: softinstigate/restheart:latest
    container_name: restheart
    hostname: restheart
    volumes:
      - /etc/restheart:/opt/restheart/etc
    command: ["--envFile", "/opt/restheart/etc/default.properties"]
    networks:
      api-network:
        aliases:
          - restheart
          - restheart.api-network
      db-network:
        aliases:
          - restheart
          - restheart.db-network

networks:
  api-network:
    external: true
  db-network:
    external: true
```

## Environment

Ubuntu 20.04 (at AWS)
Mongo 4.4.6
Authentication and authorization using mongo instead of file. Others configurations are the default.

## Steps to Reproduce

1. docker-compose -f compose-file.yml up

**Comment by ujibang** [comment]
Hi @mcardia 

I cannot reproduce it.

Please configure the logging with the following configuration (for help see [custom logback configuration](https://restheart.org/docs/logging/#specify-a-custom-logback-configuration) ) and reproduce the error. 

Then paste the full exception to this thread.

1. Add the file `/opt/restheart/etc/logback.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <withJansi>true</withJansi>
        <encoder>
            <pattern>%d{HH:mm:ss.SSS} [%thread] %highlight(%-5level) %logger{36} - %msg%n %throwable</pattern>
        </encoder>
    </appender>

    <root level="ERROR">
        <appender-ref ref="STDOUT" />
    </root>

    <logger name="org.restheart" level="ALL"/>
</configuration>
```

2. Add to the docker compose the  following `entrypoint` to the restheart service

```yml
services:
  restheart:
    image: softinstigate/restheart:latest
    container_name: restheart
    hostname: restheart
    entrypoint: [ "java", "-Dfile.encoding=UTF-8", "-Dlogback.configurationFile=etc/logback.xml", "-server", "-jar", "restheart.jar", "etc/restheart.yml"]
```
