### ISSUE TITLE
PUT with key produces 404 error

### ISSUE THREAD

**Issue by dmushkov** [SoftInstigate/restheart#423]
Hello as state in docs 

PUT /inventory/newItem HTTP/1.1

{ "item": "pencil", "qty": 55, "size": { "h": 10, "w": 0.5, "uom": "cm" }, "status": "B", "suppliers": ["brand_1", "brand_2", "brand_3"] }
should create document with _id = newItem

In snapshot version restheart-snapshot:0e920df (which I use for auth filter)
I got 404 error when try to execute above request

**Comment by ujibang** [comment]
The write mode semantic changed with RESTHeart v6. In previous releases all write verbs have upsert semantic. In v6:

- POST verb has insert write mode
- PUT and PATCH verbs have update write mode

So a PUT against a not existent document results in `404 Not Found` (you cannot update an not existing document)

Have a look at https://restheart.org/docs/upgrade-to-v6/#write-mode-in-mongodb-rest-api

The write mode can be controlled with the `wm` query parameter.

To insert a document with PUT you need to specify `?wm=insert` or `?wm=upsert` but take into account that the user needs a special permission to use this query param (the `root` role can use it):

```yml
- role: user
      predicate: path-prefix('/coll')
      mongo:
        allowWriteMode: true
```

The rational behind this is to radically simplify the definition of security permissions which is mandatory for developing real world applications.

Take into account the following permission:

```yml
- role: user
      predicate: path-prefix('/coll') and method(POST)
      mongo:
        mergeRequest: >
          {"author": "@user.userid" }
```

In v5 it allowed the user to insert and modify any document in the collection `coll`. In v6 it only allows to insert new documents. It also sets the field `author` to be equal to the user id.

The following permission allows the user to modify only documents created by her:

```yml
- role: user
      predicate: path-template('/coll/{id}') and method(PATCH)
      mongo:
        writeFilter: >
            {"author": "@user.userid"}
```
