### ISSUE TITLE
Mount static resource to "/" blocks mongo mounts

### ISSUE THREAD

**Issue by austinrappa78** [SoftInstigate/restheart#431]
When upgrading to v6 the static resource path now blocks any mongo-mounts within the same path.

## Expected Behavior
With RESTHeart running:
1. The website www.blahblahblah.com serves up static content from static-resources-mounts
2. The website www.blahblahblah.com/api serves the MongoDB collections

## Current Behavior
The website www.blahblahblah.com serves up static content from static-resources-mounts
The website www.blahblahblah.com/api returns 404 errors

## Context
Upgrading from v3 to v6 and this behavior has changed.

## Environment
Assume the folder structure:
- \www
    - index.html
- restheart.jar 
 
In the restheart.yml configuration file:
```
mongo-mounts:
    - what: "*"
      where: /api

static-resources-mounts:
    - what: /www
      where: /
      welcome-file: index.html
      secured: false
      embedded: false
```

## Steps to Reproduce
Make changes to restheart.yml. Use curl or postman.
