### ISSUE TITLE
RESTHeart v8.3.1 does not work with FerretDB v2

### ISSUE THREAD

**Issue by qdrddr** [SoftInstigate/restheart#537]
**Describe the bug**

When running this docker-compose.yaml with image `ferretdb:1.24.0` all is good. But when replaced with `ferretdb:2.0.0-rc.1` and trying to work with the DB by executing this command in shell `http -a "admin:secret" PUT :8080/` I'm getting an error: 

```log
http -a "admin:secret" PUT :8080/
HTTP/1.1 500 Internal Server Error
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ETag, Auth-Token, Auth-Token-Valid-Until, Auth-Token-Location, X-Powered-By
Connection: keep-alive
Content-Length: 440
Content-Type: application/json

{
    "exception": "java.lang.RuntimeException",
    "exception message": "java.util.concurrent.ExecutionException: com.mongodb.MongoSecurityException: Exception authenticating MongoCredential{mechanism=PLAIN, userName='username', source='ferretdb', password=<hidden>, mechanismProperties=<hidden>}",
    "http status code": 500,
    "http status description": "Internal Server Error",
    "message": "Error handling the request, see logs for more information"
}
```

**To Reproduce**

```yaml
# docker compose -f docker-compose.yaml up -d
# rm -r ./data
services:
  postgres:
    # https://hub.docker.com/_/postgres/tags?name=17.2
    image: postgres:17.2-bookworm
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ferretdb
    volumes:
      - ./data:/var/lib/postgresql/data

  ferretdb:
    # https://github.com/ferretdb/FerretDB/pkgs/container/ferretdb
    #image: ghcr.io/ferretdb/ferretdb:1.24.0
    image: ghcr.io/ferretdb/ferretdb:2.0.0-rc.1
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://postgres:5432/ferretdb

  restheart:
    # https://hub.docker.com/r/softinstigate/restheart/tags?name=8.3
    image: softinstigate/restheart:8.3.1-distroless
    environment:
      RHO: >
        /mclient/connection-string->"mongodb://username:password@ferretdb/ferretdb?authMechanism=PLAIN"; /http-listener/host->"0.0.0.0";
    depends_on:
      - ferretdb
    ports:
      - "8080:8080"

networks:
  default:
    name: ferretdb
```

**Expected behavior**

`http -a "admin:secret" PUT :8080/` supposed to return `HTTP/1.1 200 OK`:
```
HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location, ETag, Auth-Token, Auth-Token-Valid-Until, Auth-Token-Location, X-Powered-By
Auth-Token: 4l2b19wpqvrtfn2gofmzymy0p8mz4wzs47kyojc9icqsvyzsgr
Auth-Token-Location: /tokens/admin
Auth-Token-Valid-Until: 2025-01-31T02:50:39.349051342Z
Connection: keep-alive
Content-Length: 0
Content-Type: application/json
Date: Fri, 31 Jan 2025 02:35:39 GMT
ETag: 679c36fbfb61272ed2d522a6
X-Powered-By: restheart.org
```

**Additional context**

logs from the ferretdb & restheart attached:
[restheart.log](https://github.com/user-attachments/files/18612480/restheart.log)
[FerretDB.log](https://github.com/user-attachments/files/18612481/FerretDB.log)

**Comment by AlekSi** [comment]
FerretDB v2 completely reworked authentication; we rely on PostgreSQL for that now. The `PLAIN` authentication mechanism is not supported anymore. See https://docs.ferretdb.io/security/authentication/

**Comment by qdrddr** [comment]
When I try to connect to the db with mongosh to ferretdb v2, I got an error: 
```shell
mongosh --version
2.3.8

mongosh mongodb://username:password@127.0.0.1:27017/
Current Mongosh Log ID: 679cf1f108d16b1874da7469
Connecting to:          mongodb://<credentials>@127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.3.8
MongoServerError: schema "documentdb_api" does not exist
```

**Comment by qdrddr** [comment]
and this still does not work. I have tried both FERRETDB_POSTGRESQL_URL with username & password and without
```yaml
services:
  postgres:
    image: postgres:17.2-bookworm
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ferretdb
    volumes:
      - ./data:/var/lib/postgresql/data

  ferretdb:
    #image: ghcr.io/ferretdb/ferretdb:1.24.0
    image: ghcr.io/ferretdb/ferretdb:2
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      - FERRETDB_POSTGRESQL_URL=postgres://postgres:5432/ferretdb
      #- FERRETDB_POSTGRESQL_URL=postgres://username:password@postgres:5432/postgres


  restheart:
    image: softinstigate/restheart:8.3.1-distroless
    environment:
      RHO: >
        /mclient/connection-string->"mongodb://username:password@ferretdb/ferretdb?authMechanism=SCRAM-SHA-256"; /http-listener/host->"0.0.0.0";
    depends_on:
      - ferretdb
    ports:
      - "8080:8080"

networks:
  default:
    name: ferretdb
```

**Comment by mkjsix** [comment]
I have tested successfully restheart 8.3.1 + ferredb v2 with this docker compose file:

```yaml
services:
  postgres:
    image: ghcr.io/ferretdb/postgres-documentdb:16
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  ferretdb:
    image: ghcr.io/ferretdb/ferretdb:2
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      FERRETDB_POSTGRESQL_URL: postgres://username:password@postgres:5432/postgres

  restheart:
    image: softinstigate/restheart
    environment:
      RHO: >
        /mclient/connection-string->"mongodb://username:password@ferretdb/ferretdb"; /http-listener/host->"0.0.0.0";
    depends_on:
      ferretdb:
        condition: service_healthy
    ports:
      - "8080:8080"

networks:
  default:
    name: ferretdb
```
