### ISSUE TITLE
Question: how to see existing databases

### ISSUE THREAD

**Issue by thoefkens** [SoftInstigate/restheart#539]
Hi all,

I have set up restheart to connect to mongo using via Docker:

```/mclient/connection-string->"mongodb://admin:password@mongodb:27017/?authSource=admin";```

Once I start up mongo and restheart I can only see the "acl" and "users" Endpoints when I curl localhost:8080

However, I do not seem to be able to get restheart to show existing databases and collections in my MongoDb.

When I call localhost:8080/db it tells me the collection does not exist - even though there is a database db in mongo which the admin user can access (as configured above). 

Restheart seems to shows me only the collections in the "restheart" database it created. 
I already tried setting an ACL with all db access in the restheart acl collecition - and in Mongo, the admin user has all rights on all databases.

What am I misconfiguring?

Thank you
Thomas

**Comment by mkjsix** [comment]
Hi @thoefkens 

For security reasons the [default RESTHeart's configuration](https://restheart.org/docs/default-configuration#mongoservice-mongodb-rest-and-websocket-api) only mounts the "restheart" database.

```yaml
  mongo-mounts:
    - what: /restheart
      where: /
```

If you look at the above link there's an example in a comment:

```yaml
  # Examples:
  # The following exposes all MongoDb resources.
  # In this case the URI of a document is /db/coll/docid
  #
mongo-mounts:
  - what: "*"
    where: /
```

Have a look [here](https://restheart.org/docs/configuration#modify-the-configuration-with-the-rho-env-var) for examples on how to set the proper RHO environment variable.

In your case this should work:

`/mclient/connection-string->"mongodb://admin:password@mongodb:27017/?authSource=admin"; /mongo/mongo-mounts[1]->{"where: "/", "what": "*"}'`
