### ISSUE TITLE
Connect to existing database using docker

### ISSUE THREAD

**Issue by deepaksainii** [SoftInstigate/restheart#549]
I want to connect to existing mongo database using docker,
it is only creating **restheart** database and creating collection in it. but i want to connect with exisitng database. 
I am using the  following yml file
```
services:
  restheart:
    image: softinstigate/restheart
    container_name: restheart
    networks:
      - restheart-network
    ports:
      - "8080:8080"
    environment:
      - RHO=/http-listener/host->"0.0.0.0";/mclient/connection-string->"mongodb+srv://username:password@url/calls?authSource=admin&retryWrites=true&w=majority"
    restart: always

networks:
  restheart-network:
    driver: bridge
```

**Comment by yanniswa** [comment]
I did it like the following to connect to an existing Database:
```
 RHO: >
          /mclient/connection-string->"mongodb://yourUser:yourPassword@mongodb:27017/yourDatabase?replicaSet=rs0&authSource=admin";
          /http-listener/host->"0.0.0.0";
          /mongo/mongo-mounts[1] -> {"where": "/api", "what": "yourDatabase"};
```

**Comment by ujibang** [comment]
In the configuration file you have

```yml
# Use mongo-mounts to expose MongoDb resources binding them to API URIs.
  #
  # The parameter 'what' identifies the MongoDb resource to expose.
  # The format is /db[/coll[/docid]]
  # Use the wildcard '*' to expose all dbs.
  #
  # The parameter 'where' defines the URI to bind the resource to.
  # It can be an absolute path (eg. /api) or path template (eg. /{foo}/bar/*).
  # The values of the path templates properties are available:
  # - in the 'what' property (e.g. what: /{foo}_db/coll)
  # - programmatically from MongoRequest.getPathTemplateParamenters() method.
  #
  # It is not possible to mix absolute paths and path templates: 'where' URIs
  # need to be either all absolute paths or all path templates.
  #
  # Examples:
  # The following exposes all MongoDb resources.
  # In this case the URI of a document is /db/coll/docid
  #
  #   - what: "*"
  #     where: /
  #
  # The following binds the URI /database to the db 'db'
  # In this case the URI of a document is /database/coll/docid
  #
  #   - what: /db
  #     where: /database
  #
  # The following binds the URI /api to the collection 'db.coll'
  # In this case the URI of a document is /api/docid
  #
  #   - what: /db/coll
  #     where: /api
  mongo-mounts:
    - what: /restheart
      where: /
```
